CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    pass TEXT NOT NULL,
    joindate DATE DEFAULT now(),
    isadmin BOOLEAN NOT NULL DEFAULT FALSE,
    email TEXT,
    savedrecipes TEXT,
    savedcooklists TEXT,
    buddylist TEXT,
    received TEXT
);